# -*- coding: utf-8 -*-
"""AI_Movie_Trailer_Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o1lpTGwe0-jxt7trZuqSOy6-kKbIFROU

# 🎬 AI Movie Trailer Generator

**Generate a cinematic trailer for ANY movie using AI!**

**Built with:** Google Gemini · ElevenLabs · Pexels · Pollinations AI · MoviePy

---

## 🚀 How to Use
1. Add your API keys in **Cell 2**
2. Enter your movie details in **Cell 3** ← only thing you change!
3. Go to **Runtime → Change runtime type → T4 GPU**
4. Click **Runtime → Run All**

## 🔑 API Keys Required
| Key | Get it here | Free? |
|---|---|---|
| `GEMINI_API_KEY` | [aistudio.google.com](https://aistudio.google.com) | ✅ Free |
| `PEXELS_API_KEY` | [pexels.com/api](https://www.pexels.com/api/) | ✅ Free |
| `ELEVENLABS_API_KEY` | [elevenlabs.io](https://elevenlabs.io) | ✅ 10k chars/month |

---
> ⚠️ **Never share your API keys publicly on GitHub!**

## 📦 Cell 1 — Install Dependencies
"""

!pip install -q google-genai elevenlabs moviepy pillow requests nest_asyncio
!apt-get install -y fonts-liberation > /dev/null 2>&1
print("✅ All dependencies installed!")

"""## 🔑 Cell 2 — API Keys"""

# ⚠️ Replace with your actual API keys — never share publicly!
GEMINI_API_KEY     = "Enter you API key"
PEXELS_API_KEY     = "Enter you API key"
ELEVENLABS_API_KEY = "Enter you API key"

print("✅ API Keys set!")

"""## 🎬 Cell 3 — YOUR Movie Details
> ✏️ **THIS IS THE ONLY CELL YOU NEED TO CHANGE!**  
> Enter your movie title, genre and story below.

"""

# ============================================================
# ✏️ ENTER YOUR MOVIE DETAILS HERE
# ============================================================

movie_title = input("🎬 Enter Movie Title: ")
genre       = input("🎭 Enter Genre (e.g. Sci-Fi Action Thriller): ")

print("\\n📖 Now enter your movie story.")
print("Press Enter twice when done.\\n")

lines = []
while True:
    line = input()
    if line == "" and lines and lines[-1] == "":
        break
    lines.append(line)
story = "\\n".join(lines[:-1])

print("\\n🎥 Enter 5 scene keywords for video search (one per line):")
PEXELS_SEARCH_TERMS = []
for i in range(5):
    term = input(f"  Scene {i+1}: ")
    PEXELS_SEARCH_TERMS.append(term)

print("\\n🖼️ Enter 3 scene descriptions for AI images (one per line):")
scene_descriptions = []
for i in range(3):
    desc = input(f"  Image {i+1}: ")
    scene_descriptions.append(desc + ", cinematic, 4K, dramatic lighting")

print("\\n" + "─"*50)
print(f"✅ Movie  : {movie_title}")
print(f"✅ Genre  : {genre}")
print(f"✅ Story  : {len(story.split())} words")
print(f"✅ Scenes : {len(PEXELS_SEARCH_TERMS)} clips")
print(f"✅ Images : {len(scene_descriptions)} AI images")
print("─"*50)
print("\\n▶️ Now run Cell 4 onwards!")

"""## 💾 Cell 4 — Mount Google Drive"""

from google.colab import drive
import os

drive.mount('/content/drive')
save_dir = f"/content/drive/MyDrive/AI_Trailer_{movie_title.replace(' ','_')}"
os.makedirs(save_dir, exist_ok=True)
os.makedirs("/content/sample_data", exist_ok=True)

print(f"✅ Google Drive mounted!")
print(f"📁 Backup folder: My Drive → AI_Trailer_{movie_title.replace(' ','_')}")

"""## 🤖 Cell 5 — Generate Trailer Script (Gemini)"""

from google import genai

client = genai.Client(api_key=GEMINI_API_KEY)

trailer_prompt = f"""
You are a Hollywood trailer scriptwriter.
Based on this movie story, write a cinematic trailer script.

Movie Title: {movie_title}
Genre: {genre}

Story:
{story}

Write EXACTLY 3 scenes in this format:

Scene 1:
Visual: [dramatic description of what appears on screen]
Narration: [powerful one or two line voice-over]

Scene 2:
Visual: [dramatic description of what appears on screen]
Narration: [powerful one or two line voice-over]

Scene 3:
Visual: [dramatic description of what appears on screen]
Narration: [most powerful closing line of the trailer]

Background Music Mood: [describe music feel]

Make it extremely dramatic, intense and cinematic.
"""

trailer_response = client.models.generate_content(
    model="gemini-2.5-flash",
    contents=trailer_prompt
)

trailer_script = trailer_response.text
print("🎬 TRAILER SCRIPT GENERATED!")
print("─" * 60)
print(trailer_script)

"""## 🎙️ Cell 6 — Generate 45-Second Narration (Gemini)"""

narration_prompt = f"""
You are a Hollywood trailer voice-over artist.
Write a powerful 45-second cinematic trailer narration for this movie.

Rules:
- Total spoken words: exactly 100-110 words (= ~45 seconds)
- Structure:
  * 0-10s:  Dark mysterious opening
  * 10-25s: Rising danger and chaos
  * 25-38s: Hero mission revealed
  * 38-45s: Explosive closing line
- Use ... for dramatic pauses
- Short punchy sentences
- No scene numbers, no headers, just pure narration text

Movie: {movie_title}
Genre: {genre}
Story: {story}
"""

narration_response = client.models.generate_content(
    model="gemini-2.5-flash",
    contents=narration_prompt
)

narration_text = narration_response.text
word_count = len(narration_text.split())
print("🎙️ NARRATION GENERATED!")
print("─" * 60)
print(narration_text)
print(f"\n📊 Word count : {word_count} words")
print(f"⏱️  Estimated  : ~{word_count//2} seconds")

"""## 🔊 Cell 7 — Generate Voice-Over (ElevenLabs)"""

from elevenlabs.client import ElevenLabs
from moviepy.editor import AudioFileClip
from IPython.display import Audio
import os

os.makedirs("/content/sample_data", exist_ok=True)

client_el = ElevenLabs(api_key=ELEVENLABS_API_KEY)

with open("/content/sample_data/trailer_voice.mp3", "wb") as f:
    response = client_el.text_to_speech.convert(
        text=narration_text,
        voice_id="ErXwobaYiN019PkySvjV",   # Antoni — deep cinematic voice
        model_id="eleven_multilingual_v2",
        output_format="mp3_44100_128"
    )
    for chunk in response:
        if chunk:
            f.write(chunk)

duration = AudioFileClip("/content/sample_data/trailer_voice.mp3").duration
print(f"✅ Voice generated! Duration: {duration:.1f}s")

# Preview
Audio("/content/sample_data/trailer_voice.mp3")

"""## 🎨 Cell 8 — Generate Scene Images (Pollinations)"""

import requests, urllib.parse, time
from IPython.display import display, Image as IPImage

print(f"🎨 Generating {len(scene_descriptions)} story-matched images...\n")
scene_image_paths = []

for i, desc in enumerate(scene_descriptions, start=1):
    print(f"  🖼️  Generating Scene {i}...")
    generated = False

    for seed in [i*42, i*99, i*77]:
        encoded = urllib.parse.quote(desc)
        url = f"https://image.pollinations.ai/prompt/{encoded}?width=1024&height=576&nologo=true&enhance=true&seed={seed}"
        try:
            r = requests.get(url, timeout=90)
            if r.status_code == 200:
                path = f"/content/sample_data/scene_{i}.png"
                with open(path, "wb") as f:
                    f.write(r.content)
                scene_image_paths.append(path)
                print(f"  ✅ Scene {i} saved!")
                display(IPImage(path, width=512))
                generated = True
                break
        except Exception as e:
            print(f"  ⚠️  Seed {seed} failed: {e}")

    if not generated:
        print(f"  ❌ Scene {i} failed!")
    time.sleep(3)

print(f"\n✅ {len(scene_image_paths)} images ready!")

"""## 🎥 Cell 9 — Fetch Video Clips (Pexels — Free)"""

import requests, time

print(f"🎥 Fetching {len(PEXELS_SEARCH_TERMS)} video clips...\n")
pexels_clip_paths = []

for i, search_term in enumerate(PEXELS_SEARCH_TERMS, start=1):
    print(f"  🎥 Scene {i}: '{search_term}'")

    def fetch_video(query):
        return requests.get(
            "https://api.pexels.com/videos/search",
            headers={"Authorization": PEXELS_API_KEY},
            params={"query": query, "per_page": 10,
                    "orientation": "landscape", "size": "medium",
                    "min_duration": 5, "max_duration": 30}
        )

    response = fetch_video(search_term)
    if response.status_code != 200:
        print(f"  ❌ Error: {response.status_code}")
        continue

    videos = response.json().get("videos", [])
    if not videos:
        print(f"  ⚠️  No results — trying generic backup...")
        response = fetch_video("cinematic dramatic")
        videos = response.json().get("videos", [])

    if not videos:
        print(f"  ❌ No videos found for Scene {i}")
        continue

    best_video = None
    for video in videos:
        hd = [v for v in video["video_files"]
              if v.get("quality") == "hd" and v.get("width", 0) >= 1280]
        if hd:
            best_video = hd[0]
            break
    if not best_video:
        files = videos[0]["video_files"]
        sd = [v for v in files if v.get("quality") in ["hd","sd"]]
        best_video = sd[0] if sd else files[0]

    video_path = f"/content/sample_data/pexels_clip_{i}.mp4"
    r = requests.get(best_video["link"], stream=True)
    with open(video_path, "wb") as f:
        for chunk in r.iter_content(chunk_size=8192):
            f.write(chunk)

    pexels_clip_paths.append(video_path)
    print(f"  ✅ Scene {i} saved — HD!")
    time.sleep(1)

print(f"\n✅ {len(pexels_clip_paths)} clips downloaded!")

def add_vignette(clip, color="dark", intensity=0.7):
    import numpy as np

    def vignette_frame(frame):
        img = frame.astype(np.float32)
        h, w = img.shape[:2]

        Y, X = np.ogrid[:h, :w]
        cx, cy = w//2, h//2
        dist = np.sqrt(((X-cx)/cx)**2 + ((Y-cy)/cy)**2)
        mask = np.clip(1 - dist * intensity, 0, 1)

        if color == "red":
            img[:,:,0] *= np.clip(mask + 0.3, 0, 1)
            img[:,:,1] *= mask
            img[:,:,2] *= mask
        else:
            for c in range(3):
                img[:,:,c] *= mask

        return np.clip(img, 0, 255).astype(np.uint8)

    return clip.fl_image(vignette_frame)

# Auto pick vignette based on genre
genre_lower = genre.lower()
if any(x in genre_lower for x in ["horror","thriller"]):
    all_clips = [add_vignette(c, color="red") for c in all_clips]
    print("✅ Red vignette added!")
else:
    all_clips = [add_vignette(c, color="dark") for c in all_clips]
    print("✅ Dark vignette added!")

# Add this in Cell 6 after narration generation
overlay_prompt = f"""
From this movie story pick exactly 5 most dramatic SHORT phrases.
Each must be under 4 words.
Return ONLY in this format — one per line, nothing else:
Line 1
Line 2
Line 3
Line 4
Line 5

Story: {story}
"""

overlay_response = client.models.generate_content(
    model="gemini-2.5-flash",
    contents=overlay_prompt
)

overlay_lines = [line.strip() for line in
                 overlay_response.text.strip().split('\n')
                 if line.strip()][:5]

print("📝 Text overlays:")
for line in overlay_lines:
    print(f"  → {line}")

"""## 🎞️ Cell 10 — Build Final Trailer (MoviePy)"""

def make_title_card(title, subtitle, duration, card_type="intro"):
    canvas = Image.new("RGB", (OUTPUT_W, OUTPUT_H), (0, 0, 0))
    draw   = ImageDraw.Draw(canvas)

    # ── Deep cinematic gradient (very dark) ───────────────
    for y in range(OUTPUT_H):
        ratio = y / OUTPUT_H
        r = int(5 + 15 * (1 - ratio))
        g = int(0 + 5  * (1 - ratio))
        b = int(10 + 20 * (1 - ratio))
        draw.line([(0, y), (OUTPUT_W, y)], fill=(r, g, b))

    # ── Subtle vignette edges (darker corners) ────────────
    for i in range(80):
        alpha = int(180 * (1 - i/80))
        draw.rectangle([i, i, OUTPUT_W-i, OUTPUT_H-i],
                       outline=(0, 0, 0))

    # ── Horizontal light streak across middle ─────────────
    for i in range(3):
        y = OUTPUT_H // 2 - 40 + i * 80
        draw.line([(0, y), (OUTPUT_W, y)],
                  fill=(30, 20, 10), width=1)

    # ── Thin gold border lines ────────────────────────────
    gold = (180, 140, 40)
    draw.line([(60, 30), (OUTPUT_W-60, 30)],    fill=gold, width=1)
    draw.line([(60, OUTPUT_H-30), (OUTPUT_W-60, OUTPUT_H-30)], fill=gold, width=1)

    # ── Small corner marks ────────────────────────────────
    cs = 20
    for cx, cy in [(60,30),(OUTPUT_W-60,30),(60,OUTPUT_H-30),(OUTPUT_W-60,OUTPUT_H-30)]:
        draw.rectangle([cx-2, cy-2, cx+2, cy+2], fill=gold)

    # ── Fonts ─────────────────────────────────────────────
    try:
        fp = "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf"
        fr = "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf"
        ft = ImageFont.truetype(fp, 100)   # big bold title
        fs = ImageFont.truetype(fr, 22)    # thin subtitle
        fc = ImageFont.truetype(fr, 13)    # tiny details
        fl = ImageFont.truetype(fp, 14)    # small caps genre
    except:
        ft = fs = fc = fl = ImageFont.load_default()

    # ── TITLE — all caps, gold, centered ─────────────────
    title_upper = title.upper()
    bbox = ft.getbbox(title_upper)
    tw = bbox[2] - bbox[0]

    # Shadow layers for depth
    for offset in [(4,4),(3,3),(2,2)]:
        draw.text(((OUTPUT_W-tw)//2 + offset[0],
                   OUTPUT_H//2 - 80 + offset[1]),
                  title_upper, font=ft, fill=(20, 10, 0))

    # Main gold title
    draw.text(((OUTPUT_W-tw)//2, OUTPUT_H//2 - 80),
              title_upper, font=ft, fill=(220, 180, 50))

    # Subtle white highlight on top of title
    draw.text(((OUTPUT_W-tw)//2 - 1, OUTPUT_H//2 - 81),
              title_upper, font=ft, fill=(255, 230, 120))

    # ── Thin divider line ─────────────────────────────────
    lw = min(tw + 40, OUTPUT_W - 120)
    lx = (OUTPUT_W - lw) // 2
    draw.line([(lx, OUTPUT_H//2 + 30), (lx + lw, OUTPUT_H//2 + 30)],
              fill=(180, 140, 40), width=1)

    # ── Subtitle — spaced out thin text ──────────────────
    subtitle_upper = subtitle.upper()
    # Add letter spacing effect
    spaced = "  ".join(subtitle_upper)
    bbox2 = fs.getbbox(spaced)
    sw = bbox2[2] - bbox2[0]
    draw.text(((OUTPUT_W - sw) // 2, OUTPUT_H//2 + 42),
              spaced, font=fs, fill=(180, 170, 150))

    # ── Genre tag (intro only) ────────────────────────────
    if card_type == "intro":
        tag = genre.upper()
        spaced_tag = " · ".join(tag.split())
        bbox3 = fl.getbbox(spaced_tag)
        gw = bbox3[2] - bbox3[0]
        draw.text(((OUTPUT_W - gw) // 2, OUTPUT_H//2 - 115),
                  spaced_tag, font=fl, fill=(150, 130, 80))

        # Small line above genre
        draw.line([((OUTPUT_W-gw)//2 - 20, OUTPUT_H//2 - 120),
                   ((OUTPUT_W+gw)//2 + 20, OUTPUT_H//2 - 120)],
                  fill=(100, 80, 30), width=1)

    # ── Bottom credits line ───────────────────────────────
    credit = "AN  AI  GENERATED  FILM  EXPERIENCE"
    bbox4 = fc.getbbox(credit)
    cw = bbox4[2] - bbox4[0]
    draw.text(((OUTPUT_W - cw) // 2, OUTPUT_H - 45),
              credit, font=fc, fill=(80, 70, 50))

    # ── Year (outro only) ─────────────────────────────────
    if card_type == "outro":
        year = "2025"
        byear = fc.getbbox(year)
        yw = byear[2] - byear[0]
        draw.text(((OUTPUT_W - yw) // 2, OUTPUT_H//2 + 75),
                  year, font=fc, fill=(120, 100, 60))

    return ImageClip(np.array(canvas)).set_duration(duration).fadein(1.2).fadeout(1.0)

"""## 💾 Cell 11 — Save to Google Drive"""

import shutil, glob, os

skip = ['.csv', '.json', '.md']
saved = 0

for f in glob.glob("/content/sample_data/*"):
    if not any(x in f for x in skip):
        try:
            shutil.copy(f, save_dir)
            print(f"✅ Saved: {os.path.basename(f)}")
            saved += 1
        except Exception as e:
            print(f"⚠️  Skipped: {e}")

print(f"\n💾 {saved} files backed up!")
print(f"📁 Location: My Drive → AI_Trailer_{movie_title.replace(' ','_')}")

"""## ▶️ Cell 12 — Watch Your Trailer!"""

from IPython.display import HTML
import base64

with open("/content/sample_data/trailer_output.mp4", "rb") as f:
    b64 = base64.b64encode(f.read()).decode()

HTML(f'''
<h2 style="color:gold;font-family:Arial;text-align:center">🎬 {movie_title} — Official Trailer</h2>
<video width="960" height="540" controls autoplay style="border:2px solid gold;">
  <source src="data:video/mp4;base64,{b64}" type="video/mp4">
</video>
''')

"""## ⬇️ Cell 13 — Download Trailer to PC"""

from google.colab import files
files.download("/content/sample_data/trailer_output.mp4")
print(f"✅ Downloading: {movie_title} trailer!")

"""## 🔄 Cell 14 — Restore Files After Disconnect
> Run this if Colab disconnects. Restores all files from Drive.  
> Then just run **Cell 1 → Cell 3** for variables, then **Cell 10** directly!

"""

import shutil, glob, os

os.makedirs("/content/sample_data", exist_ok=True)
restore_dir = f"/content/drive/MyDrive/AI_Trailer_{movie_title.replace(' ','_')}"

files = glob.glob(f"{restore_dir}/*")
if files:
    for f in files:
        shutil.copy(f, "/content/sample_data/")
        print(f"✅ Restored: {os.path.basename(f)}")
    print(f"\n🎉 {len(files)} files restored!")
    print("▶️  Now run Cell 1→3 for variables, then Cell 10!")
else:
    print("⚠️  No backup found — run all cells from start!")